to know more about numpy
### Link :https://numpy.org/devdocs//user/basics.broadcasting.html

In [1]:
import numpy as np

In [2]:
# printing random numbers
data = np.random.randint(0,20,10) #(start,stop,no of outputs)

In [3]:
data

array([ 3,  8,  5, 10, 13, 12,  9,  0,  8, 18])

In [4]:
#also can perform arthematic functions
data+5

array([ 8, 13, 10, 15, 18, 17, 14,  5, 13, 23])

In [5]:
data-5

array([-2,  3,  0,  5,  8,  7,  4, -5,  3, 13])

In [6]:
data*5

array([15, 40, 25, 50, 65, 60, 45,  0, 40, 90])

In [10]:
#to print in a matrix form
np.random.randint(0,10,(3,3))

array([[7, 3, 2],
       [4, 4, 5],
       [8, 0, 3]])

In [11]:
np.random.randint(0,10,(3,5))

array([[1, 6, 4, 7, 1],
       [9, 6, 0, 9, 0],
       [5, 0, 7, 4, 0]])

In [12]:
np.random.randint(0,10,(10,5))

array([[9, 9, 3, 5, 6],
       [9, 0, 2, 7, 3],
       [2, 8, 9, 2, 1],
       [6, 5, 9, 3, 8],
       [7, 7, 8, 0, 3],
       [0, 3, 1, 9, 9],
       [5, 4, 8, 9, 9],
       [5, 2, 0, 7, 9],
       [3, 7, 1, 4, 0],
       [7, 6, 9, 9, 6]])

In [13]:
x=np.random.randint(0,10,(3,3))
x

array([[4, 3, 6],
       [3, 1, 0],
       [8, 0, 1]])

In [14]:
y=np.random.randint(0,10,(3,3))
y

array([[2, 9, 8],
       [7, 9, 0],
       [5, 6, 8]])

In [15]:
x+y # can perform arthematic function

array([[ 6, 12, 14],
       [10, 10,  0],
       [13,  6,  9]])

In [16]:
data = np.random.randint(0,10,(10,5),)

In [17]:
data

array([[9, 4, 0, 4, 4],
       [2, 3, 1, 0, 6],
       [1, 1, 9, 2, 3],
       [2, 3, 9, 3, 1],
       [4, 6, 1, 8, 5],
       [8, 0, 9, 4, 2],
       [4, 5, 7, 2, 6],
       [4, 0, 2, 0, 1],
       [3, 1, 0, 3, 8],
       [6, 8, 2, 9, 2]])

In [18]:
data.shape #returns rows and columns

(10, 5)

In [19]:
data.cumsum() #adds all the integers one by one

array([  9,  13,  13,  17,  21,  23,  26,  27,  27,  33,  34,  35,  44,
        46,  49,  51,  54,  63,  66,  67,  71,  77,  78,  86,  91,  99,
        99, 108, 112, 114, 118, 123, 130, 132, 138, 142, 142, 144, 144,
       145, 148, 149, 149, 152, 160, 166, 174, 176, 185, 187])

In [20]:
x=np.random.randint(0,10,5)
print(x)
x.cumsum()

[9 4 0 5 2]


array([ 9, 13, 13, 18, 20])

In [21]:
print(x)
x.cumprod() #multiplies all the integers one by one

[9 4 0 5 2]


array([ 9, 36,  0,  0,  0])

In [22]:
data=np.random.randint(0,10,(3,3))

In [23]:
data

array([[9, 5, 9],
       [5, 0, 2],
       [3, 2, 4]])

In [24]:
data.cumsum(axis=0) # adds the integers one by one according to axis 0 means rows and 1 is columns

array([[ 9,  5,  9],
       [14,  5, 11],
       [17,  7, 15]])

In [25]:
np.zeros((3,3)) # prints all zeros in a matrix form

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((3,3)) # applicable for only zeros and ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a=np.random.choice([10,20,30,40,50],size=3)
a
#print random no from an array of its choice

array([40, 30, 50])

In [28]:
data=np.random.randint(0,10,(3,3))

In [29]:
data

array([[3, 7, 5],
       [7, 3, 8],
       [3, 4, 5]])

In [30]:
data.sum() #returns sum of all the elements

np.int64(45)

In [32]:
data.sum(axis=1) #returns the sum according to axis; 1=column

array([15, 18, 12])

In [37]:
data.sum(axis=1).max()

np.int64(18)

In [33]:
data.sum(axis=0) #returns the sum according to axis; 0=rows

array([13, 14, 18])

In [38]:
data.sum(axis=0).max()

np.int64(18)

In [34]:
np.argmin(data) #returns the index of min element

np.int64(0)

In [35]:
np.argmax(data) #returns the index of max element

np.int64(5)

# **stats in numpy**

In [39]:
data=np.random.randint(0,10,10)

In [40]:
data

array([7, 3, 8, 6, 2, 9, 9, 4, 1, 0])

In [42]:
data.mean() #returns the average

np.float64(4.9)

In [44]:
np.median(data)

np.float64(5.0)

In [48]:
#to get mode we need spicy.stats
import numpy as np
from scipy import stats

stats.mode(data)

ModeResult(mode=np.int64(9), count=np.int64(2))

In [49]:
np.quantile(data,0.25) #returns the first quartile

np.float64(2.25)

In [50]:
np.quantile(data,0.50) #returns the half quartile which is equal to median

np.float64(5.0)

In [51]:
np.median(data)

np.float64(5.0)

In [52]:
np.quantile(data,0.75) #returns the last quartile

np.float64(7.75)

In [54]:
np.std(data) # returns the variation in dataset

np.float64(3.176476034853718)

In [55]:
np.var(data)

np.float64(10.09)

In [58]:
data=np.random.randint(0,10,(3,3))
np.corrcoef(data.T)
#returns the co-relation coeffiency

array([[1.        , 1.        , 0.92857143],
       [1.        , 1.        , 0.92857143],
       [0.92857143, 0.92857143, 1.        ]])