In [5]:
import numpy as np

In [6]:
data = np.random.randint(0,10,(4,4))
data

array([[9, 5, 8, 6],
       [7, 9, 7, 1],
       [7, 6, 7, 4],
       [8, 0, 1, 1]])

In [7]:
data.sum()

np.int64(86)

In [8]:
data.sum(axis=0) # axis 0 means y axis

array([31, 20, 23, 12])

In [9]:
data.sum(axis=1) # axis 1 means x axis

array([28, 24, 24, 10])

In [10]:
data.max()

np.int64(9)

In [11]:
data.min()

np.int64(0)

In [12]:
data.argmax() # index of max value

np.int64(0)

In [13]:
data.argmin() # index of min value

np.int64(13)

In [14]:
data.max(axis=0) # returns max element

array([9, 9, 8, 6])

In [15]:
data.argmax(axis=0)# returns index of max value in that axis

array([0, 1, 0, 0])

In [16]:
data.max(axis=1)

array([9, 9, 7, 8])

In [17]:
data.argmax(axis=1)

array([0, 1, 0, 0])

In [18]:
data

array([[9, 5, 8, 6],
       [7, 9, 7, 1],
       [7, 6, 7, 4],
       [8, 0, 1, 1]])

In [19]:
data.min(axis=0)

array([7, 0, 1, 1])

In [20]:
data.min(axis=0).sum()

np.int64(9)

In [21]:
data.argmin(axis=0)

array([1, 3, 3, 1])

In [22]:
data.argmin(axis=0).sum()

np.int64(8)

In [23]:
data=np.random.randint(0,10,(10,5))

In [24]:
data

array([[6, 5, 0, 8, 8],
       [5, 6, 4, 1, 1],
       [7, 8, 4, 9, 3],
       [4, 7, 4, 2, 5],
       [9, 2, 1, 9, 4],
       [3, 4, 5, 0, 4],
       [5, 7, 6, 7, 4],
       [5, 6, 1, 4, 0],
       [8, 7, 8, 2, 7],
       [1, 5, 5, 3, 1]])

In [25]:
data.sum(axis=0)

array([53, 57, 38, 45, 37])

In [26]:
data.sum(axis=1)

array([27, 17, 31, 22, 25, 16, 29, 16, 32, 15])

In [27]:
data.max(axis=0)

array([9, 8, 8, 9, 8])

In [28]:
data.max(axis=1)

array([8, 6, 9, 7, 9, 5, 7, 6, 8, 5])

In [29]:
data.sum()

np.int64(230)

In [30]:
data.max(axis=0).sum()

np.int64(42)

In [31]:
data.max(axis=1).sum()

np.int64(70)

In [36]:
#to get only selected column and row
data[0:7,:]

array([[6, 5, 0, 8, 8],
       [5, 6, 4, 1, 1],
       [7, 8, 4, 9, 3],
       [4, 7, 4, 2, 5],
       [9, 2, 1, 9, 4],
       [3, 4, 5, 0, 4],
       [5, 7, 6, 7, 4]])

In [37]:
data[0:7,:].sum()

np.int64(167)

In [47]:
#another way
data.sum(axis=0)[:7]

array([53, 57, 38, 45, 37])

In [39]:
data.sum(axis=0)[0:7].sum()

np.int64(230)

In [55]:
data=np.random.randint(0,10,10)
data

array([4, 1, 3, 8, 9, 6, 6, 7, 0, 9])

In [56]:
data.mean()

np.float64(5.3)

In [57]:
np.median(data)

np.float64(6.0)

In [58]:
np.mean(data)

np.float64(5.3)

In [59]:
np.quantile(data,0.25)

np.float64(3.25)

In [61]:
np.quantile(data,0.50)

np.float64(6.0)

In [60]:
np.quantile(data,0.75)

np.float64(7.75)

In [62]:
np.std(data)

np.float64(3.0347981810987035)

In [63]:
np.var(data)

np.float64(9.209999999999999)