In [3]:
import numpy as np

In [4]:
# Retail dataset as numpy array

retail_np_array = np.array([
    [1001, "Laptop", 1, 50000, 50000],
    [1002, "Mouse", 2, 500, 1000],
    [1003, "Keyboard", 1, 1000, 1000],
    [1004, "Monitor", 2, 7000, 14000],
    [1005, "Headphones", 1, 2000, 2000]
], dtype=object)

retail_np_array

array([[1001, 'Laptop', 1, 50000, 50000],
       [1002, 'Mouse', 2, 500, 1000],
       [1003, 'Keyboard', 1, 1000, 1000],
       [1004, 'Monitor', 2, 7000, 14000],
       [1005, 'Headphones', 1, 2000, 2000]], dtype=object)

In [5]:
# Extracting columns

customer_ids = retail_np_array[:, 0]

products = retail_np_array[:, 1]

quantities = retail_np_array[:, 2].astype(int)

prices = retail_np_array[:, 3].astype(int)

totals = retail_np_array[:, 4].astype(int)


In [6]:
customer_ids

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [7]:
products

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
      dtype=object)

In [8]:
quantities

array([1, 2, 1, 2, 1])

In [9]:
prices

array([50000,   500,  1000,  7000,  2000])

In [10]:
totals

array([50000,  1000,  1000, 14000,  2000])

In [11]:
customer_ids1 = retail_np_array[:, 0]
customer_ids1

array([1001, 1002, 1003, 1004, 1005], dtype=object)

In [12]:
retail_np_array.shape # returns the shape like rows and coloumns

(5, 5)

In [13]:
print("1. Total number of transactions: ",retail_np_array.shape[0])

1. Total number of transactions:  5


In [14]:
print("2. Total revenue generated: ",np.sum(totals))

2. Total revenue generated:  68000


In [15]:
print("3. Average order value: ",np.mean(totals))

3. Average order value:  13600.0


In [16]:
print("4. Product with the highest total price: ",products [np.argmax(totals)])

4. Product with the highest total price:  Laptop


In [17]:
print("5. Product with the lowest total price: ",products [np.argmin(totals)])

5. Product with the lowest total price:  Mouse


In [18]:
print("6. Average price of products: ",np.mean (prices))

6. Average price of products:  12100.0


In [19]:
print("7. Total quantity sold: ",np.sum (quantities),)

7. Total quantity sold:  7


In [20]:
print("8. Most frequently purchased product: ",np.unique(products, return_counts=True)[0][np.argmax(np.unique(products, return_counts=True)[1])])

8. Most frequently purchased product:  Headphones


In [21]:
print("9. Number of unique products : ",len (np.unique (products)),)

9. Number of unique products :  5


In [22]:
print("10. Number of unique customers: ",len(np.unique(customer_ids)))

10. Number of unique customers:  5


In [23]:
print("11. List all products sold: ",products.tolist())

11. List all products sold:  ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones']


In [24]:
print("12. Revenue per product: ",{prod: np.sum(totals[products == prod]) for prod in np.unique(products)},)

12. Revenue per product:  {'Headphones': np.int64(2000), 'Keyboard': np.int64(1000), 'Laptop': np.int64(50000), 'Monitor': np.int64(14000), 'Mouse': np.int64(1000)}


In [25]:
print("13. Quantity sold per product : ",{prod: np.sum(quantities[products == prod]) for prod in np.unique(products)})

13. Quantity sold per product :  {'Headphones': np.int64(1), 'Keyboard': np.int64(1), 'Laptop': np.int64(1), 'Monitor': np.int64(2), 'Mouse': np.int64(2)}


In [26]:
print("14. Highest price of a product : ",np.max(prices),)

14. Highest price of a product :  50000


In [27]:
print("15. Lowest price of a product : ",np.min(prices))

15. Lowest price of a product :  500


In [30]:
print("16. Products sold more than once : ",products[quantities > 1].tolist())

16. Products sold more than once :  ['Mouse', 'Monitor']


In [31]:
print("17. Customers who bought more than one item : ",customer_ids[quantities > 1])

17. Customers who bought more than one item :  [1002 1004]


In [32]:
print("18. Total spent by CustomerID 1002 : ",np.sum(totals[customer_ids == 1002]))

18. Total spent by CustomerID 1002 :  1000


In [34]:
print("19. Products priced above 1000 : ",products[prices > 1000])

19. Products priced above 1000 :  ['Laptop' 'Monitor' 'Headphones']


In [35]:
print("20. Products with total >= 2000 : ",products[totals >= 2000])

20. Products with total >= 2000 :  ['Laptop' 'Monitor' 'Headphones']
